name: Gauge Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Gauge
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge --version
          gauge telemetry off
          gauge install python
          gauge install html-report
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Run Gauge specs
        run: |
          mkdir -p reports logs screenshots
          gauge run specs/ --env ci
        env:
          HEADLESS: true
          BROWSER: chromium
          MAXIMIZED: true
          
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports/
          retention-days: 5