name: Gauge Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Check workspace structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
            
      - name: Install Gauge
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          echo "PATH=$HOME/.gauge/bin:$PATH" >> $GITHUB_ENV
          gauge --version
          gauge telemetry off
          gauge install python
          gauge install html-report
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
            
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
      
      - name: Create environment directories
        run: |
          # 创建必要的环境目录
          mkdir -p env/ci
          echo "Created directories:"
          ls -la
          ls -la env/
          
          # 创建CI环境配置文件
          cat > env/ci/default.properties << 'EOL'
          # CI环境配置
          
          # 浏览器配置
          BROWSER=chromium
          HEADLESS=true
          SLOW_MO=0
          VIEWPORT_WIDTH=1366
          VIEWPORT_HEIGHT=768
          TRACE=false
          MAXIMIZED=true
          
          # 报告配置
          overwrite_reports=true
          screenshot_on_failure=true
          EOL
          
          # 创建Python属性文件
          cat > env/ci/python.properties << 'EOL'
          GAUGE_PYTHON_COMMAND = python
          
          # Comma seperated list of dirs. path should be relative to project root.
          STEP_IMPL_DIR = step_impl
          EOL
          
          echo "Created config files:"
          cat env/ci/default.properties
          cat env/ci/python.properties
          
      - name: Run Gauge specs
        run: |
          mkdir -p reports logs screenshots
          gauge run specs/ -v --env ci
        env:
          HEADLESS: true
          BROWSER: chromium
          MAXIMIZED: true
            
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports/
          retention-days: 5